trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore app/SamlApp/SamlApp.csproj
  displayName: 'Restore NuGet packages'

- script: dotnet build app/SamlApp/SamlApp.csproj --configuration Release
  displayName: 'Build project'

- script: dotnet test app/SamlApp.Tests/SamlApp.Tests.csproj --configuration Release
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
