# azure-pipelines.yml
# CI Pipeline for SAML Sample App

trigger:
  branches:
    include:
      - main   # 🚨 You can comment this out while testing

pool:
  vmImage: 'windows-latest'   # Use Windows agent for .NET 8

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      displayName: "Install .NET 8 SDK"
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet --version
      displayName: "Check .NET version"

    - script: dotnet restore app/SamlApp/SamlApp.csproj
      displayName: "Restore packages"

    - script: dotnet build app/SamlApp/SamlApp.csproj --c
